# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main      

jobs:
  build-discovery-service:
    needs: [start-zipkin]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: 'success'

      - name: Build Discovery Service
        run: cd backend-application/discovery-service && mvn clean install

  build-cloud-gateway-service:
    needs: [start-zipkin, build-discovery-service]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: 'success'

      - name: Build Cloud Gateway Service
        run: cd backend-application/cloud-gateway-service && mvn clean install

  build-favourite-service:
    needs: [start-mysql-favourite-db, start-zipkin, build-discovery-service, build-cloud-gateway-service]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true
          job-status: 'success'

      - name: Build Favourite Service
        run: cd backend-application/favourite-service && mvn clean install
      
  start-zipkin:
    runs-on: ubuntu-latest
    container:
      image: openzipkin/zipkin
      ports:
        - 9414:9411
    timeout-minutes: 5
    
  start-mysql-favourite-db:
    runs-on: ubuntu-latest
    container:
      image: mysql:8
      env:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: favourite
      ports:
        - 33064:3306
      options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    timeout-minutes: 5

  push-to-docker-hub:
    needs: [build-discovery-service, build-cloud-gateway-service, build-favourite-service]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKE }}

      - name: Build and push Docker images
        run: |
          docker-compose build
          docker-compose push

