name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk-security:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - discovery-service
          - favourite-service
          - cloud-gateway-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: 'x64'
          
       # Run Snyk Open Source (SCA) analysis and uploads result to Snyk
      - name: Snyk Open Source Monitor Before Test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd backend-application/${{ matrix.service }}
          mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
          snyk monitor --all-projects

      - name: Snyk Code test - Run Snyk to check for vulnerabilities (focuses on identifying security issues within the source code of the projec)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd backend-application/${{ matrix.service }}
          mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
          snyk code test --all-projects --sarif-file-output=snyk-code-${{ matrix.service }}.sarif

      - name: Snyk Code test - Run Snyk to check for vulnerabilities (checks for vulnerabilities in project dependencies)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          cd backend-application/${{ matrix.service }}
          mvn dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml" > dependency-tree.dot
          snyk code test --sarif > snyk-code.sarif || true
          snyk test --all-projects --sarif-file-output=snyk-test.sarif

      - name: Upload Snyk test results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: backend-application/${{ matrix.service }}/snyk-test.sarif
